name: zsdemo_app
description: Sales demo app for presenting the functionalities of the zsfinder
  android service

publish_to: "none" # Remove this line if you wish to publish to pub.dev

# version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  camera: ^0.10.1
  csv: ^5.0.2
  cupertino_icons: ^1.0.2
  data_table_2: ^2.5.8
  device_apps: ^2.2.0
  device_info_plus: ^9.0.3
  dio: ^5.1.2
  either_option: ^2.0.0
  equatable: ^2.0.5
  fixnum: ^1.1.0
  flutter:
    sdk: flutter
  flutter_file_dialog: ^3.0.2
  flutter_keyboard_visibility: ^5.4.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.14
  flutter_secure_storage: ^8.0.0
  flutter_web_auth: ^0.5.0
  geolocator: ^9.0.2
  google_mlkit_barcode_scanning: ^0.6.0
  hex: ^0.2.0
  http: ^0.13.6
  intersperse: ^2.0.0
  intl: ^0.18.0
  open_filex: ^4.3.2
  package_info_plus: ^4.0.0
  path_provider_android: ^2.1.0
  provider: ^6.0.5
  rxdart: ^0.27.7
  shared_preferences: ^2.1.1
  store_redirect: ^2.0.1
  uni_links: ^0.5.1
  url_launcher: ^6.1.14
  vibration: ^1.7.7

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icon/
    - assets/icons/
    - assets/files/
    - android/app/src/main/aidl/com/zebra/zsfinder/IZebraSensorService.aidl
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: icomoon
      fonts:
        - asset: assets/icons/icons.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
  class_name: Loco

flutter_icons:
  android: true
  ios: false
  image_path_android: "assets/icon/zsdemo-adaptive-icon-preview.png"
  adaptive_icon_background: "assets/icon/zsdemo-adaptive-icon-background.png"
  adaptive_icon_foreground: "assets/icon/zsdemo-adaptive-icon-foreground.png"
